export const payload = {
  "Meezan Bank": [
    {
      "Emp.code": "123",
      "Emp Name": "John Doe",
      "Join Date": "xx-yy-zzzz",
      City: "Karachi",
      "Invoince #": "1234",
      "Cheque Amt": "2132123",
      "Cheque #": "12312312",
      "Pay Date": "01-Oct-2022",
      "Last Date": "01-Oct-2022",
      Remarks:
        "Testing Remarks.Testing RemarksTesting RemarksTesting RemarksTesting Remarks",
      "In Words": "",
    },
    {
      "Emp.code": "1212434534",
      "Emp Name": "John Doe",
      "Join Date": "xx-yy-zzzz",
      City: "Karachi",
      "Invoince #": "1234",
      "Cheque Amt": "2132123",
      "Cheque #": "12312312",
      "Pay Date": "01-Oct-2022",
      "Last Date": "01-Oct-2022",
      Remarks:
        "Testing Remarks.Testing RemarksTesting RemarksTesting RemarksTesting Remarks",
      "In Words": "",
    },
    {
      "Emp.code": "67456",
      "Emp Name": "John Doe",
      "Join Date": "xx-yy-zzzz",
      City: "Karachi",
      "Invoince #": "1234",
      "Cheque Amt": "2132123",
      "Cheque #": "12312312",
      "Pay Date": "01-Oct-2022",
      "Last Date": "01-Oct-2022",
      Remarks:
        "Testing Remarks.Testing RemarksTesting RemarksTesting RemarksTesting Remarks",
      "In Words": "",
    },
  ],
  "Test Bank": [
    {
      "Emp.code": "1234",
      "Emp Name": "John Doe",
      "Join Date": "xx-yy-zzzz",
      City: "Karachi",
      "Invoince #": "1234",
      "Cheque Amt": "2132123",
      "Cheque #": "12312312",
      "Pay Date": "01-Oct-2022",
      "Last Date": "01-Oct-2022",
      Remarks:
        "Testing Remarks.Testing RemarksTesting RemarksTesting RemarksTesting Remarks",
      "In Words": "",
    },
    {
      "Emp.code": "1234",
      "Emp Name": "John Doe",
      "Join Date": "xx-yy-zzzz",
      City: "Karachi",
      "Invoince #": "1234",
      "Cheque Amt": "2132123",
      "Cheque #": "12312312",
      "Pay Date": "01-Oct-2022",
      "Last Date": "01-Oct-2022",
      Remarks:
        "Testing Remarks.Testing RemarksTesting RemarksTesting RemarksTesting Remarks",
      "In Words": "",
    },
    {
      "Emp.code": "1234",
      "Emp Name": "John Doe",
      "Join Date": "xx-yy-zzzz",
      City: "Karachi",
      "Invoince #": "1234",
      "Cheque Amt": "2132123",
      "Cheque #": "12312312",
      "Pay Date": "01-Oct-2022",
      "Last Date": "01-Oct-2022",
      Remarks:
        "Testing Remarks.Testing RemarksTesting RemarksTesting RemarksTesting Remarks",
      "In Words": "",
    },
  ],
};
