export const payload = {
  data: {
    "Sindh Modarba": [
      {
        "sr#": 1,
        Date: "2022-09-01",
        "Invoice#": 1,
        Description:
          'Processed "Testing" for the month of "September 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "Sindh Modarba",
        "For Month": "September",
        "Service Charges": 0,
      },
      {
        "sr#": 3,
        Date: "2022-10-01",
        "Invoice#": 3,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 79843,
        "Income Tax": 1492,
        Payout: 53871.85,
        "Invoice Credited": 25000,
        Balance: 28871.85,
        Status: "Pending",
        Organization: "Sindh Modarba",
        "For Month": "October",
        "Service Charges": 4790.58,
      },
    ],
    "LMK Resources Pakistan (Private) Limited": [
      {
        "sr#": 2,
        Date: "2022-10-30",
        "Invoice#": 2,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "LMK Resources Pakistan (Private) Limited - Janitorial Services - Sindh"',
        "# of Staff": 591,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "LMK Resources Pakistan (Private) Limited",
        "For Month": "October",
        "Service Charges": 0,
      },
    ],
    "Sindh Modarba1": [
      {
        "sr#": 1,
        Date: "2022-09-01",
        "Invoice#": 1,
        Description:
          'Processed "Testing" for the month of "September 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "Sindh Modarba",
        "For Month": "September",
        "Service Charges": 0,
      },
      {
        "sr#": 3,
        Date: "2022-10-01",
        "Invoice#": 3,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 79843,
        "Income Tax": 1492,
        Payout: 53871.85,
        "Invoice Credited": 25000,
        Balance: 28871.85,
        Status: "Pending",
        Organization: "Sindh Modarba",
        "For Month": "October",
        "Service Charges": 4790.58,
      },
    ],
    "LMK Resources Pakistan (Private) Limited1": [
      {
        "sr#": 2,
        Date: "2022-10-30",
        "Invoice#": 2,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "LMK Resources Pakistan (Private) Limited - Janitorial Services - Sindh"',
        "# of Staff": 591,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "LMK Resources Pakistan (Private) Limited",
        "For Month": "October",
        "Service Charges": 0,
      },
    ],
    "Sindh Modarba2": [
      {
        "sr#": 1,
        Date: "2022-09-01",
        "Invoice#": 1,
        Description:
          'Processed "Testing" for the month of "September 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "Sindh Modarba",
        "For Month": "September",
        "Service Charges": 0,
      },
      {
        "sr#": 3,
        Date: "2022-10-01",
        "Invoice#": 3,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 79843,
        "Income Tax": 1492,
        Payout: 53871.85,
        "Invoice Credited": 25000,
        Balance: 28871.85,
        Status: "Pending",
        Organization: "Sindh Modarba",
        "For Month": "October",
        "Service Charges": 4790.58,
      },
    ],
    "LMK Resources Pakistan (Private) Limited2": [
      {
        "sr#": 2,
        Date: "2022-10-30",
        "Invoice#": 2,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "LMK Resources Pakistan (Private) Limited - Janitorial Services - Sindh"',
        "# of Staff": 591,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "LMK Resources Pakistan (Private) Limited",
        "For Month": "October",
        "Service Charges": 0,
      },
    ],
    "Sindh Modarba3": [
      {
        "sr#": 1,
        Date: "2022-09-01",
        "Invoice#": 1,
        Description:
          'Processed "Testing" for the month of "September 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "Sindh Modarba",
        "For Month": "September",
        "Service Charges": 0,
      },
      {
        "sr#": 3,
        Date: "2022-10-01",
        "Invoice#": 3,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "Sindh Modarba - Administration - Sindh"',
        "# of Staff": 1,
        "Invoice Amount": 79843,
        "Income Tax": 1492,
        Payout: 53871.85,
        "Invoice Credited": 25000,
        Balance: 28871.85,
        Status: "Pending",
        Organization: "Sindh Modarba",
        "For Month": "October",
        "Service Charges": 4790.58,
      },
    ],
    "LMK Resources Pakistan (Private) Limited3": [
      {
        "sr#": 2,
        Date: "2022-10-30",
        "Invoice#": 2,
        Description:
          'Processed "Regular Payroll" for the month of "October 2022" for "LMK Resources Pakistan (Private) Limited - Janitorial Services - Sindh"',
        "# of Staff": 591,
        "Invoice Amount": 0,
        "Income Tax": 0,
        Payout: 0,
        "Invoice Credited": 0,
        Balance: 0,
        Status: "Paid",
        Organization: "LMK Resources Pakistan (Private) Limited",
        "For Month": "October",
        "Service Charges": 0,
      },
    ],
  },
};
