export const testing = {
  data: {
    2022: {
      August: [
        {
          EmployeeMaster: {
            "Employee #": "0020004",
            "Employee Name": "Ahmed",
            DOJ: "2022-01-01T00:00:00+00:00",
            Designation: "IT Support  Staff",
            Department: "Designing",
            "Bank Account No": "4949",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 150000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 0,
              eobi_employee: 1,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 200,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 0,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 7502.5,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 0,
              essi_ded: 19000,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0020002",
            "Employee Name": "Muhammad Hussain",
            DOJ: "2022-01-01T00:00:00+00:00",
            Designation: "GDC",
            Department: "Admin",
            "Bank Account No": "01040102059161",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 100000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 1,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 200,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 780,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 2501.6666666666665,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 19000,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0020003",
            "Employee Name": "Ali",
            DOJ: "2022-01-01T00:00:00+00:00",
            Designation: "GDC",
            Department: "OMC",
            "Bank Account No": "4949",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 125000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 1,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 200,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 780,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 5001.666666666667,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 19000,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
      ],
      July: [
        {
          EmployeeMaster: {
            "Employee #": "0020004",
            "Employee Name": "Ahmed",
            DOJ: "2022-01-01T00:00:00+00:00",
            Designation: "IT Support  Staff",
            Department: "Designing",
            "Bank Account No": "4949",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 150000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 1,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 200,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 780,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 7502.5,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 19000,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0040476",
            "Employee Name": "Muhammad Israr",
            DOJ: "2021-02-02T04:00:00+00:00",
            Designation: "Attendant",
            Department: "Finance",
            "Bank Account No": "3177729610",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 21000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 0,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 0,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 1260,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 0,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 0,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0040494",
            "Employee Name": "Ashfaq Ahmad",
            DOJ: "2021-02-17T04:00:00+00:00",
            Designation: "Attendant",
            Department: "Finance",
            "Bank Account No": "3119068936",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 21000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 0,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 0,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 1260,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 0,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 0,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0040514",
            "Employee Name": "Saeed Ullah Jan",
            DOJ: "2021-03-20T04:00:00+00:00",
            Designation: "Attendant",
            Department: "Finance",
            "Bank Account No": "3161195132",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 21000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 0,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 0,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 1260,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 0,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 0,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0040533",
            "Employee Name": "Syed Jan",
            DOJ: "2021-05-27T04:00:00+00:00",
            Designation: "Attendant",
            Department: "Finance",
            "Bank Account No": "3179584125",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 21000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 0,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 0,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 1260,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 0,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 0,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0040552",
            "Employee Name": "Mehran Khan",
            DOJ: "2021-07-18T04:00:00+00:00",
            Designation: "Attendant",
            Department: "Finance",
            "Bank Account No": "3189750277",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 21000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 0,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 0,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 1260,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 0,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 0,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0040583",
            "Employee Name": "Nasir Khan",
            DOJ: "2022-02-04T04:00:00+00:00",
            Designation: "Attendant",
            Department: "Finance",
            "Bank Account No": "null",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 21500,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 0,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 0,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 1290,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 0,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 0,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
        {
          EmployeeMaster: {
            "Employee #": "0040588",
            "Employee Name": "Safi Ullah",
            DOJ: "2022-03-09T04:00:00+00:00",
            Designation: "Attendant",
            Department: "Finance",
            "Bank Account No": "54897000035103",
            "Bank Name": "Meezan Bank",
          },
          PayrollData: {
            allowance: {
              Salary: 21000,
              attendance_allowance: 0,
              overtime: 0,
              eobi_employer: 650,
              eobi_employee: 0,
              commission: 0,
              incentive: 0,
              bonus: 0,
              arrears_taxable: 0,
              arrears_nontaxable: 0,
              uniform_claim_amount: 0,
              special_allow1: 0,
              special_allow2: 0,
              gli_premium: 0,
              cli_premium: 0,
              ghi_premium: 0,
              essi_amount: 1260,
            },
            deduction: {
              other_deduction: 0,
              income_tax: 0,
              gli_ded: 0,
              cli_ded: 0,
              ghi_ded: 0,
              eobi_ded: 130,
              essi_ded: 0,
              medical_ded: 0,
              canteen_ded: 0,
              transportation_ded: 0,
              accommodation_ded: 0,
              facility01_ded: 0,
              facility02_ded: 0,
              facility03_ded: 0,
              facility04_ded: 0,
              facility05_ded: 0,
              other01_ded: 0,
              other02_ded: 0,
              other03_ded: 0,
              fixed01_ded: 0,
              fixed02_ded: 0,
              fixed03_ded: 0,
              fixed04_ded: 0,
              fixed05_ded: 0,
              incometax_ded: 0,
            },
          },
        },
      ],
    },
  },
};
